### ISSUE TITLE
yeoman auto generator

### ISSUE THREAD

**Issue by zenithtekla** [esatemre/meanjs-mysql#1]
Hi,
Does yeoman auto generator work with your stack?
Or how do I configure (downgrade if required) to get it to work? generating new controllers, models, routes, views, .. automatically by copying user and article patterns.

Thanks

**Comment by guohuang** [comment]
First of all, Good choice on ditching MongoDB, I have asked the same question, I don't think the current version support yoman, you will be stuck with the  current version. You will have to manually copy the files yourself.

Thanks

**Comment by esatemre** [comment]
Unfortunately, There is no "yo generator" for this refined version yet.

Thanks for interest.
